/*
 * Todoist API
 * Custom Todoist API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mmcgarvey.todoist.client.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * TaskToCreate
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-05T22:57:37.991-06:00")
public class TaskToCreate {
  @JsonProperty("content")
  private String content = null;

  @JsonProperty("due_date")
  private LocalDate dueDate = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("due_string")
  private String dueString = null;

  @JsonProperty("project_id")
  private BigDecimal projectId = null;

  @JsonProperty("label_ids")
  private List<Integer> labelIds = null;

  public TaskToCreate content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(value = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public TaskToCreate dueDate(LocalDate dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Get dueDate
   * @return dueDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getDueDate() {
    return dueDate;
  }

  public void setDueDate(LocalDate dueDate) {
    this.dueDate = dueDate;
  }

  public TaskToCreate priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * minimum: 1
   * maximum: 4
   * @return priority
  **/
  @ApiModelProperty(value = "")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public TaskToCreate dueString(String dueString) {
    this.dueString = dueString;
    return this;
  }

   /**
   * Get dueString
   * @return dueString
  **/
  @ApiModelProperty(value = "")
  public String getDueString() {
    return dueString;
  }

  public void setDueString(String dueString) {
    this.dueString = dueString;
  }

  public TaskToCreate projectId(BigDecimal projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getProjectId() {
    return projectId;
  }

  public void setProjectId(BigDecimal projectId) {
    this.projectId = projectId;
  }

  public TaskToCreate labelIds(List<Integer> labelIds) {
    this.labelIds = labelIds;
    return this;
  }

  public TaskToCreate addLabelIdsItem(Integer labelIdsItem) {
    if (this.labelIds == null) {
      this.labelIds = new ArrayList<>();
    }
    this.labelIds.add(labelIdsItem);
    return this;
  }

   /**
   * Get labelIds
   * @return labelIds
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getLabelIds() {
    return labelIds;
  }

  public void setLabelIds(List<Integer> labelIds) {
    this.labelIds = labelIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskToCreate taskToCreate = (TaskToCreate) o;
    return Objects.equals(this.content, taskToCreate.content) &&
        Objects.equals(this.dueDate, taskToCreate.dueDate) &&
        Objects.equals(this.priority, taskToCreate.priority) &&
        Objects.equals(this.dueString, taskToCreate.dueString) &&
        Objects.equals(this.projectId, taskToCreate.projectId) &&
        Objects.equals(this.labelIds, taskToCreate.labelIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, dueDate, priority, dueString, projectId, labelIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskToCreate {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    dueString: ").append(toIndentedString(dueString)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    labelIds: ").append(toIndentedString(labelIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

