/*
 * Todoist API
 * Custom Todoist API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mmcgarvey.todoist.client.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.mmcgarvey.todoist.client.models.Due;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Task
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-05T22:57:37.991-06:00")
public class Task {
  @JsonProperty("comment_count")
  private Integer commentCount = null;

  @JsonProperty("completed")
  private Boolean completed = null;

  @JsonProperty("content")
  private String content = null;

  @JsonProperty("due")
  private Due due = null;

  @JsonProperty("id")
  private BigDecimal id = null;

  @JsonProperty("indent")
  private Integer indent = null;

  @JsonProperty("label_ids")
  private List<Integer> labelIds = null;

  @JsonProperty("order")
  private Integer order = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("project_id")
  private BigDecimal projectId = null;

  @JsonProperty("url")
  private String url = null;

  public Task commentCount(Integer commentCount) {
    this.commentCount = commentCount;
    return this;
  }

   /**
   * Get commentCount
   * @return commentCount
  **/
  @ApiModelProperty(value = "")
  public Integer getCommentCount() {
    return commentCount;
  }

  public void setCommentCount(Integer commentCount) {
    this.commentCount = commentCount;
  }

  public Task completed(Boolean completed) {
    this.completed = completed;
    return this;
  }

   /**
   * Get completed
   * @return completed
  **/
  @ApiModelProperty(value = "")
  public Boolean isCompleted() {
    return completed;
  }

  public void setCompleted(Boolean completed) {
    this.completed = completed;
  }

  public Task content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(value = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public Task due(Due due) {
    this.due = due;
    return this;
  }

   /**
   * Get due
   * @return due
  **/
  @ApiModelProperty(value = "")
  public Due getDue() {
    return due;
  }

  public void setDue(Due due) {
    this.due = due;
  }

  public Task id(BigDecimal id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getId() {
    return id;
  }

  public void setId(BigDecimal id) {
    this.id = id;
  }

  public Task indent(Integer indent) {
    this.indent = indent;
    return this;
  }

   /**
   * Get indent
   * @return indent
  **/
  @ApiModelProperty(value = "")
  public Integer getIndent() {
    return indent;
  }

  public void setIndent(Integer indent) {
    this.indent = indent;
  }

  public Task labelIds(List<Integer> labelIds) {
    this.labelIds = labelIds;
    return this;
  }

  public Task addLabelIdsItem(Integer labelIdsItem) {
    if (this.labelIds == null) {
      this.labelIds = new ArrayList<>();
    }
    this.labelIds.add(labelIdsItem);
    return this;
  }

   /**
   * Get labelIds
   * @return labelIds
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getLabelIds() {
    return labelIds;
  }

  public void setLabelIds(List<Integer> labelIds) {
    this.labelIds = labelIds;
  }

  public Task order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @ApiModelProperty(value = "")
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public Task priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @ApiModelProperty(value = "")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public Task projectId(BigDecimal projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getProjectId() {
    return projectId;
  }

  public void setProjectId(BigDecimal projectId) {
    this.projectId = projectId;
  }

  public Task url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Task task = (Task) o;
    return Objects.equals(this.commentCount, task.commentCount) &&
        Objects.equals(this.completed, task.completed) &&
        Objects.equals(this.content, task.content) &&
        Objects.equals(this.due, task.due) &&
        Objects.equals(this.id, task.id) &&
        Objects.equals(this.indent, task.indent) &&
        Objects.equals(this.labelIds, task.labelIds) &&
        Objects.equals(this.order, task.order) &&
        Objects.equals(this.priority, task.priority) &&
        Objects.equals(this.projectId, task.projectId) &&
        Objects.equals(this.url, task.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commentCount, completed, content, due, id, indent, labelIds, order, priority, projectId, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Task {\n");
    
    sb.append("    commentCount: ").append(toIndentedString(commentCount)).append("\n");
    sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    due: ").append(toIndentedString(due)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    indent: ").append(toIndentedString(indent)).append("\n");
    sb.append("    labelIds: ").append(toIndentedString(labelIds)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

